import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "산단 Haps",
  description: "Generated by create next app"
}
import {
  SidebarProvider,
} from "@/components/ui/sidebar"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  )
}
